import type { User, WorkWithUser } from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "田中 太郎",
    email: "tanaka@example.com",
    emailVerified: null,
    image: "https://api.dicebear.com/9.x/avataaars/svg?seed=tanaka",
  },
  {
    id: "u2",
    name: "佐藤 花子",
    email: "sato@example.com",
    emailVerified: null,
    image: "https://api.dicebear.com/9.x/avataaars/svg?seed=sato",
  },
  {
    id: "u3",
    name: "鈴木 一郎",
    email: "suzuki@example.com",
    emailVerified: null,
    image: "https://api.dicebear.com/9.x/avataaars/svg?seed=suzuki",
  },
]

export const mockWorks: WorkWithUser[] = [
  {
    id: "w1",
    userId: "u1",
    title: "タスク管理アプリ TaskFlow",
    url: "https://taskflow-demo.vercel.app",
    imageKey: "works/taskflow.png",
    techStack: ["React", "Next.js", "Supabase", "Tailwind CSS"],
    description:
      "チームでのタスク管理を効率化するWebアプリ。ドラッグ&ドロップでタスクのステータスを変更でき、リアルタイムで同期されます。",
    authorName: "田中 太郎",
    duration: "2ヶ月",
    course: "Web Expert",
    cohort: 30,
    highlight:
      "ドラッグ&ドロップのUXにこだわりました。dnd-kitを使ってスムーズなアニメーションを実現。",
    createdAt: new Date("2025-12-15"),
    updatedAt: new Date("2025-12-15"),
    user: {
      id: "u1",
      name: "田中 太郎",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=tanaka",
    },
  },
  {
    id: "w2",
    userId: "u2",
    title: "レシピ共有SNS CookShare",
    url: "https://cookshare-demo.vercel.app",
    imageKey: "works/cookshare.png",
    techStack: ["React", "Firebase", "Material UI"],
    description:
      "料理好きのためのレシピ共有SNS。写真付きでレシピを投稿し、他のユーザーのレシピにいいねやコメントができます。",
    authorName: "佐藤 花子",
    duration: "3ヶ月",
    course: "Web",
    cohort: 28,
    highlight: "画像の最適化にこだわり、WebPへの自動変換とlazy loadingを実装しました。",
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2025-11-20"),
    user: {
      id: "u2",
      name: "佐藤 花子",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=sato",
    },
  },
  {
    id: "w3",
    userId: "u3",
    title: "2Dアクションゲーム SkyRunner",
    url: "https://skyrunner-demo.netlify.app",
    imageKey: "works/skyrunner.png",
    techStack: ["Unity", "C#"],
    description:
      "空を駆け抜ける爽快2Dアクションゲーム。ランダム生成されるステージで何度でも楽しめます。",
    authorName: "鈴木 一郎",
    duration: "2ヶ月",
    course: "Game",
    cohort: 25,
    highlight: "ステージの自動生成アルゴリズムを自作し、毎回違う体験ができるようにしました。",
    createdAt: new Date("2025-10-10"),
    updatedAt: new Date("2025-10-10"),
    user: {
      id: "u3",
      name: "鈴木 一郎",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=suzuki",
    },
  },
  {
    id: "w4",
    userId: "u1",
    title: "AI画像生成ツール PixelDream",
    url: "https://pixeldream-demo.vercel.app",
    imageKey: "works/pixeldream.png",
    techStack: ["Next.js", "Python", "Stable Diffusion", "Tailwind CSS"],
    description:
      "テキストプロンプトから画像を生成するWebアプリ。生成した画像はギャラリーとして保存・共有できます。",
    authorName: "田中 太郎",
    duration: "3ヶ月",
    course: "AI",
    cohort: 29,
    highlight: null,
    createdAt: new Date("2025-09-05"),
    updatedAt: new Date("2025-09-05"),
    user: {
      id: "u1",
      name: "田中 太郎",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=tanaka",
    },
  },
  {
    id: "w5",
    userId: "u2",
    title: "ポートフォリオサイト",
    url: "https://sato-portfolio.vercel.app",
    imageKey: "works/portfolio.png",
    techStack: ["Astro", "Tailwind CSS", "Framer Motion"],
    description:
      "自分の作品や経歴をまとめたポートフォリオサイト。スクロールアニメーションで作品を印象的に見せます。",
    authorName: "佐藤 花子",
    duration: "1ヶ月",
    course: "Portfolio",
    cohort: 30,
    highlight: "Framer Motionを使ったスクロール連動アニメーションに力を入れました。",
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
    user: {
      id: "u2",
      name: "佐藤 花子",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=sato",
    },
  },
  {
    id: "w6",
    userId: "u3",
    title: "天気予報チャットボット WeatherBot",
    url: "https://weatherbot-demo.vercel.app",
    imageKey: "works/weatherbot.png",
    techStack: ["Python", "OpenAI API", "LINE Messaging API"],
    description:
      "LINEで天気を聞くと、AIが自然な文章で天気予報を教えてくれるチャットボット。",
    authorName: "鈴木 一郎",
    duration: "1.5ヶ月",
    course: "AI",
    cohort: 27,
    highlight: "OpenAI APIを使って、ただの天気情報を会話っぽく返すプロンプト設計にこだわりました。",
    createdAt: new Date("2025-08-20"),
    updatedAt: new Date("2025-08-20"),
    user: {
      id: "u3",
      name: "鈴木 一郎",
      image: "https://api.dicebear.com/9.x/avataaars/svg?seed=suzuki",
    },
  },
]
